{ pkgs, ... }:

# TV box host: KDE Plasma Bigscreen on a Mac mini (Late 2012), Macmini6,1.
#
# Hardware reality check that drives everything below:
#   CPU  Intel Core i5-3210M — 2 cores / 4 threads, Ivy Bridge
#   GPU  Intel HD Graphics 4000 (PCI 8086:0166, GT2)
#   QSV  H.264 decode+encode ONLY. No HEVC, no VP8, no VP9, no AV1.
#   Ports GbE, 4x USB 3.0, HDMI 1.4, Thunderbolt 1, SDXC
#
# So: this is a 1080p60 H.264 box. Anything VP9/AV1 (YouTube) or HEVC
# (Jellyfin remuxes) must be steered onto H.264 — see README.md in this
# directory for the per-app settings.
{
  imports = [
    ./modules/apps/fladder.nix
    ./modules/apps/vacuumtube.nix
    ./modules/graphics/intel-vaapi.nix

    # Put the TV box on the tailnet (matches hosts/desktop). Optional.
    # ../../modules/networking/netbird.nix
  ];

  # --------------------------------------------------------------- boot --
  # Apple EFI 1.x does NOT honour NVRAM boot entries, so GRUB is installed to
  # the removable-media path (EFI/BOOT/BOOTX64.EFI) and the Mac's own boot
  # picker — hold Option at boot — finds it as "EFI Boot".
  #
  # Do NOT use the legacy BIOS / CSM path: it requires a hybrid MBR, and the
  # rEFInd author's own guidance is that it "turns the boot process into a
  # coin toss". EFI mode + removable install is the supported route.
  boot.loader.grub = {
    enable = true;
    device = "nodev"; # EFI only, no MBR
    efiSupport = true;
    efiInstallAsRemovable = true;
    configurationLimit = 5; # small SSD, keep the store tidy
  };
  boot.loader.efi.canTouchEfiVariables = false;

  # ---------------------------------------------------------- firmware ---
  # BCM4331 Wi-Fi on this machine. enableAllFirmware is what pulls in the
  # b43 firmware set (enableRedistributableFirmware alone does not).
  # Wired Ethernet is still the path of least resistance — and what Moonlight
  # wants anyway. If b43 proves flaky, the alternative is broadcom_sta ("wl").
  hardware.enableAllFirmware = true;

  # 8 GB swapfile. Building Fladder's Flutter/Dart toolchain from source on a
  # 2-core CPU with 4 GB RAM does not survive without swap. Created at activation.
  # (Deliberately here rather than in hardware-configuration.nix, which gets
  # regenerated by nixos-generate-config.)
  swapDevices = [ { device = "/swapfile"; size = 8192; } ];

  # ------------------------------------------------------------ window rules --
  # Fladder opens fullscreen. It has no --fullscreen flag (only --htpc,
  # --newWindow, --skipNotifications), so force it at the window-manager level
  # instead. wmclass is the GTK application id from Fladder's
  # linux/CMakeLists.txt. KWin reads system config through the normal KConfig
  # cascade, so a rule the user adds in ~/.config/kwinrulesrc still takes
  # precedence.
  #
  # fullscreenrule=1 is "Force": KWin sets it and rejects later changes, which is
  # what stops Fladder dropping back to windowed a moment after launch. The
  # tempting 2 is "Apply" ("apply only after initial mapping") — it does
  # fullscreen the window, but then the app wins the race and un-fullscreens it.
  environment.etc."xdg/kwinrulesrc".text = ''
    [General]
    count=1
    rules=4f6d1c2e-9a3b-4c7d-8e1f-2b3c4d5e6f70

    [4f6d1c2e-9a3b-4c7d-8e1f-2b3c4d5e6f70]
    Description=Fladder fullscreen
    wmclass=nl.jknaapen.fladder
    wmclassmatch=1
    wmclasscomplete=false
    fullscreen=true
    fullscreenrule=1
  '';

  # ----------------------------------------------------------- desktop ---
  services.xserver.enable = true;
  services.desktopManager.plasma6.enable = true;

  services.displayManager.sddm.enable = true;
  services.displayManager.sddm.wayland.enable = true;

  # plasma-bigscreen ships share/wayland-sessions/plasma-bigscreen-wayland.desktop
  services.displayManager.sessionPackages = [ pkgs.kdePackages.plasma-bigscreen ];
  services.displayManager.defaultSession = "plasma-bigscreen-wayland";

  # Boot straight into the TV UI, no login prompt.
  services.displayManager.autoLogin.enable = true;
  services.displayManager.autoLogin.user = "toasty";

  # Bigscreen is PipeWire-based for audio.
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Phone-as-remote, per the Bigscreen input docs.
  programs.kdeconnect.enable = true;

  # BT remotes / game controllers.
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;

  # The Mac mini's built-in IR receiver needs no configuration — the kernel's
  # hid-appleir driver exposes it as KEY_MENU / KEY_ENTER / KEY_BACK /
  # KEY_FORWARD / KEY_VOLUMEUP / KEY_VOLUMEDOWN / KEY_PLAYPAUSE. Note the ring's
  # up/down report as *volume*, not arrows, so remap if you want D-pad
  # navigation. (This is also why the DIY TTVKTR dongle is a better remote.)

  # --------------------------------------------------------------- apps --
  # VacuumTube and Fladder are provided by ./modules/apps/*.
  environment.systemPackages = with pkgs; [
    kdePackages.plasma-bigscreen

    # 1080p60 H.264 is the sweet spot: HD 4000 decodes it in hardware.
    moonlight-qt

    firefox
    vlc
    git
    tmux
    net-tools

    # Verification: vainfo / glxinfo / intel_gpu_top
    libva-utils
    mesa-demos
    intel-gpu-tools
    pciutils
    usbutils
  ];

  # A 2-core Ivy Bridge with Plasma 6, Chromium and Electron will thank you.
  # 16 GB is the machine's max and the 2.5" bay takes any SATA SSD.
}
