keys:
  - &primary age1gjrzst2xmqd7clpmupygufkmgm2cle0x6xef3xwvjhum5vut73nsf8mhrk
  - &power age1xkhrfavhq5cg58fgnl06lm9fltcdc529h8zzlvrgezxhrv77wpzs7rd6a6
creation_rules:
  - patch_regex: authentik\.yaml$
    key_groups:
      - age:
        - *primary
        - *power
